/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { DispatchMeAppointment } from "../../types/DispatchMeAppointment";

export const CreateDispatchMeAppointment: core.serialization.Schema<
    serializers.integrations.CreateDispatchMeAppointment.Raw,
    Keet.integrations.CreateDispatchMeAppointment
> = core.serialization.object({
    appointment: DispatchMeAppointment,
});

export declare namespace CreateDispatchMeAppointment {
    interface Raw {
        appointment: DispatchMeAppointment.Raw;
    }
}
