/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { DispatchMeNote } from "../../types/DispatchMeNote";

export const CreateDispatchMeNote: core.serialization.Schema<
    serializers.integrations.CreateDispatchMeNote.Raw,
    Keet.integrations.CreateDispatchMeNote
> = core.serialization.object({
    note: DispatchMeNote,
});

export declare namespace CreateDispatchMeNote {
    interface Raw {
        note: DispatchMeNote.Raw;
    }
}
