/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const AcceptConnectionInvitation: core.serialization.Schema<
    serializers.integrations.AcceptConnectionInvitation.Raw,
    Keet.integrations.AcceptConnectionInvitation
> = core.serialization.object({
    profileUrl: core.serialization.string(),
});

export declare namespace AcceptConnectionInvitation {
    interface Raw {
        profileUrl: string;
    }
}
