/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const SendMessage: core.serialization.Schema<
    serializers.integrations.SendMessage.Raw,
    Keet.integrations.SendMessage
> = core.serialization.object({
    to: core.serialization.string(),
    content: core.serialization.string(),
});

export declare namespace SendMessage {
    interface Raw {
        to: string;
        content: string;
    }
}
