/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { XPost } from "./XPost";

export const GetXFollowingTweetsResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetXFollowingTweetsResponse.Raw,
    Keet.integrations.GetXFollowingTweetsResponse
> = core.serialization.object({
    status: ResponseStatus,
    posts: core.serialization.list(XPost),
});

export declare namespace GetXFollowingTweetsResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        posts: XPost.Raw[];
    }
}
