/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { UberAddress } from "../../types/UberAddress";
import { UberCarTypes } from "../../types/UberCarTypes";

export const OrderRide: core.serialization.Schema<serializers.integrations.OrderRide.Raw, Keet.integrations.OrderRide> =
    core.serialization.object({
        origin: UberAddress,
        destination: UberAddress,
        carType: UberCarTypes,
    });

export declare namespace OrderRide {
    interface Raw {
        origin: UberAddress.Raw;
        destination: UberAddress.Raw;
        carType: UberCarTypes.Raw;
    }
}
