/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface CreateVinLeadResponse {
    status: Keet.common.ResponseStatus;
    leadId: string;
}
