/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetSalesAppointmentResponse {
    status: Keet.common.ResponseStatus;
    appointment: Keet.integrations.vin.VinSalesAppointment;
}
