/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetVinLeadSourceResponse {
    status: Keet.common.ResponseStatus;
    leadSource: Keet.integrations.vin.VinLeadSource[];
}
