/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetVinCompanyTypeResponse {
    status: Keet.common.ResponseStatus;
    companyTypes: Keet.integrations.vin.VinCompanyType[];
}
