/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VinCustomerContactedCodes = "Y" | "N" | "M";
export const VinCustomerContactedCodes = {
    Y: "Y",
    N: "N",
    M: "M",
} as const;
