/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VinDealer {
    dealerId: number;
    dealerName: string;
    city: string;
    state: string;
    setupStatus: string;
    userIsIpRestricted: boolean;
}
