/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VinNextCallTimeSpanTypes = "Days" | "Hours" | "Months";
export const VinNextCallTimeSpanTypes = {
    Days: "Days",
    Hours: "Hours",
    Months: "Months",
} as const;
