/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VinNumberDialedCodes = "Home" | "Cell" | "Work";
export const VinNumberDialedCodes = {
    Home: "Home",
    Cell: "Cell",
    Work: "Work",
} as const;
