/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface VinSalesLocation {
    type: string;
    name: string;
    address: Keet.integrations.vin.VinSalesAddress;
}
