/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VinVehicle {
    stockNumber: string;
    year: string;
    make: string;
    model: string;
    trim?: string;
    vin: string;
    mileage: string;
    age: string;
    webPrice: string;
}
