/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "./ResponseStatus";

export const CreateSessionResponse: core.serialization.ObjectSchema<
    serializers.common.CreateSessionResponse.Raw,
    Keet.common.CreateSessionResponse
> = core.serialization.object({
    status: ResponseStatus,
    wsUrl: core.serialization.string(),
    postSignInUrl: core.serialization.string(),
});

export declare namespace CreateSessionResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        wsUrl: string;
        postSignInUrl: string;
    }
}
