/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const OfferedIntegrations: core.serialization.Schema<
    serializers.common.OfferedIntegrations.Raw,
    Keet.common.OfferedIntegrations
> = core.serialization.enum_(["Vin", "Aesthetic Records"]);

export declare namespace OfferedIntegrations {
    export type Raw = "Vin" | "Aesthetic Records";
}
