/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface CreateSessionResponse {
    status: Keet.common.ResponseStatus;
    wsUrl: string;
    postSignInUrl: string;
}
