/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface LinkConfig {
    endUserId: string;
    integration: Keet.common.OfferedIntegrations;
    companyName?: string;
    companyLogoUri?: string;
}
