/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface LinkedAccount {
    endUserId: string;
    createdAt: Date;
    integrations: Keet.common.Integration[];
}
