/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OfferedIntegrations =
    | "Venmo"
    | "LinkedIn"
    | "Amazon Business"
    | "Amazon"
    | "Uber"
    | "Instagram"
    | "X"
    | "DoorDash";

export const OfferedIntegrations = {
    Venmo: "Venmo",
    LinkedIn: "LinkedIn",
    AmazonBusiness: "Amazon Business",
    Amazon: "Amazon",
    Uber: "Uber",
    Instagram: "Instagram",
    X: "X",
    DoorDash: "DoorDash",
} as const;
