/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OfferedIntegrations = "Vin" | "Aesthetic Records";

export const OfferedIntegrations = {
    Vin: "Vin",
    AestheticRecords: "Aesthetic Records",
} as const;
