/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const PostGroupMessage: core.serialization.Schema<
    serializers.integrations.PostGroupMessage.Raw,
    Keet.integrations.PostGroupMessage
> = core.serialization.object({
    message: core.serialization.string(),
});

export declare namespace PostGroupMessage {
    interface Raw {
        message: string;
    }
}
