/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KeetApi from "../../../../../index";

export interface GetTransactionsResponse {
    status: KeetApi.common.ResponseStatus;
    transactions: KeetApi.integrations.StoryResponse;
}
