/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetTransactionsResponse {
    status: Keet.common.ResponseStatus;
    transactions: string;
}
