/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface Story {
    amount: string;
    avatar: string;
    initials: string;
    audience: string;
    date: string;
    id: string;
    note: Keet.integrations.Note;
    type: string;
    attachments: unknown[];
    title: Keet.integrations.Title;
    mentions: Keet.integrations.Mentions;
    externWalletStatus?: string;
    paymentId: string;
    likes: Keet.integrations.Likes;
    comments: Keet.integrations.Comments;
    subType: string;
}
