/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KeetApi from "../../../../../index";

export interface Story {
    amount: string;
    avatar: string;
    initials: string;
    audience: string;
    date: string;
    id: string;
    note: KeetApi.integrations.Note;
    type: string;
    attachments: unknown[];
    title: KeetApi.integrations.Title;
    mentions: KeetApi.integrations.Mentions;
    externWalletStatus?: string;
    paymentId: string;
    likes: KeetApi.integrations.Likes;
    comments: KeetApi.integrations.Comments;
    subType: string;
}
