/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KeetApi from "../../../../../index";

export interface Title {
    titleType: string;
    payload: KeetApi.integrations.Payload;
    receiver: KeetApi.integrations.User;
    sender: KeetApi.integrations.User;
}
