/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface Title {
    titleType: string;
    payload: Keet.integrations.Payload;
    receiver: Keet.integrations.User;
    sender: Keet.integrations.User;
}
