/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AmazonBusinessItem {
    title: string;
    brand: string;
    price: string;
    url: string;
    pricePerUnit?: string;
    rating?: string;
    reviewCount?: string;
    imageUrl: string;
    merchant?: string;
    availability: string;
    purchaseDate?: string;
}
