/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface AmazonBusinessOrder {
    date: Date;
    total: string;
    address?: Keet.integrations.AmazonBusinessAddress;
    orderNumber: string;
    items: string[];
}
