/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetOrdersResponse {
    status: Keet.common.ResponseStatus;
    orders: Keet.integrations.Order[];
    nextPage?: number;
}
