/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { DispatchMeAddress } from "./DispatchMeAddress";
import { DispatchMePhoneNumber } from "./DispatchMePhoneNumber";

export const DispatchMeCustomer: core.serialization.ObjectSchema<
    serializers.integrations.DispatchMeCustomer.Raw,
    Keet.integrations.DispatchMeCustomer
> = core.serialization.object({
    firstName: core.serialization.string(),
    lastName: core.serialization.string(),
    organizationId: core.serialization.string(),
    companyName: core.serialization.string(),
    billingAddress: DispatchMeAddress,
    homeAddress: DispatchMeAddress,
    email: core.serialization.string(),
    notes: core.serialization.string(),
    phoneNumbers: core.serialization.list(DispatchMePhoneNumber),
    labels: core.serialization.list(core.serialization.string()),
});

export declare namespace DispatchMeCustomer {
    interface Raw {
        firstName: string;
        lastName: string;
        organizationId: string;
        companyName: string;
        billingAddress: DispatchMeAddress.Raw;
        homeAddress: DispatchMeAddress.Raw;
        email: string;
        notes: string;
        phoneNumbers: DispatchMePhoneNumber.Raw[];
        labels: string[];
    }
}
