/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const DispatchMeAppointment: core.serialization.ObjectSchema<
    serializers.integrations.DispatchMeAppointment.Raw,
    Keet.integrations.DispatchMeAppointment
> = core.serialization.object({
    duration: core.serialization.number(),
    time: core.serialization.string(),
    userId: core.serialization.number(),
    secondaryUserIds: core.serialization.list(core.serialization.number()),
    type: core.serialization.string(),
    organizationId: core.serialization.number(),
    jobId: core.serialization.number(),
});

export declare namespace DispatchMeAppointment {
    interface Raw {
        duration: number;
        time: string;
        userId: number;
        secondaryUserIds: number[];
        type: string;
        organizationId: number;
        jobId: number;
    }
}
