/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const DispatchMeNote: core.serialization.ObjectSchema<
    serializers.integrations.DispatchMeNote.Raw,
    Keet.integrations.DispatchMeNote
> = core.serialization.object({
    jobId: core.serialization.number(),
    description: core.serialization.string(),
    private: core.serialization.boolean(),
    priority: core.serialization.boolean(),
});

export declare namespace DispatchMeNote {
    interface Raw {
        jobId: number;
        description: string;
        private: boolean;
        priority: boolean;
    }
}
