/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const EditCustomerResponse: core.serialization.ObjectSchema<
    serializers.integrations.EditCustomerResponse.Raw,
    Keet.integrations.EditCustomerResponse
> = core.serialization.object({
    customer: core.serialization.unknown(),
    status: ResponseStatus,
});

export declare namespace EditCustomerResponse {
    interface Raw {
        customer?: unknown;
        status: ResponseStatus.Raw;
    }
}
