/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetAccountOrganizationsResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetAccountOrganizationsResponse.Raw,
    Keet.integrations.GetAccountOrganizationsResponse
> = core.serialization.object({
    status: ResponseStatus,
    organizations: core.serialization.unknown(),
});

export declare namespace GetAccountOrganizationsResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        organizations?: unknown;
    }
}
