/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetCustomersResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetCustomersResponse.Raw,
    Keet.integrations.GetCustomersResponse
> = core.serialization.object({
    status: ResponseStatus,
    customers: core.serialization.unknown(),
});

export declare namespace GetCustomersResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        customers?: unknown;
    }
}
