/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetDispatchMeUsersResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetDispatchMeUsersResponse.Raw,
    Keet.integrations.GetDispatchMeUsersResponse
> = core.serialization.object({
    status: ResponseStatus,
    users: core.serialization.unknown(),
});

export declare namespace GetDispatchMeUsersResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        users?: unknown;
    }
}
