/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetJobsResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetJobsResponse.Raw,
    Keet.integrations.GetJobsResponse
> = core.serialization.object({
    status: ResponseStatus,
    jobs: core.serialization.unknown(),
});

export declare namespace GetJobsResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        jobs?: unknown;
    }
}
