/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const UberAddress: core.serialization.ObjectSchema<
    serializers.integrations.UberAddress.Raw,
    Keet.integrations.UberAddress
> = core.serialization.object({
    addressLine1: core.serialization.string(),
    addressLine2: core.serialization.string(),
});

export declare namespace UberAddress {
    interface Raw {
        addressLine1: string;
        addressLine2: string;
    }
}
