/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { LinkedInConnection } from "./LinkedInConnection";

export const GetConnectionsResult: core.serialization.ObjectSchema<
    serializers.integrations.GetConnectionsResult.Raw,
    Keet.integrations.GetConnectionsResult
> = core.serialization.object({
    status: ResponseStatus,
    connections: core.serialization.list(LinkedInConnection),
});

export declare namespace GetConnectionsResult {
    interface Raw {
        status: ResponseStatus.Raw;
        connections: LinkedInConnection.Raw[];
    }
}
