/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { InvitationRequest } from "./InvitationRequest";

export const InvitationRequestsResponse: core.serialization.ObjectSchema<
    serializers.integrations.InvitationRequestsResponse.Raw,
    Keet.integrations.InvitationRequestsResponse
> = core.serialization.object({
    status: ResponseStatus,
    invitationRequests: core.serialization.list(InvitationRequest),
});

export declare namespace InvitationRequestsResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        invitationRequests: InvitationRequest.Raw[];
    }
}
