/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const InvitationRequest: core.serialization.ObjectSchema<
    serializers.integrations.InvitationRequest.Raw,
    Keet.integrations.InvitationRequest
> = core.serialization.object({
    name: core.serialization.string(),
    profileUrl: core.serialization.string(),
    sentTimeLabel: core.serialization.string(),
    description: core.serialization.string(),
    sharedConnections: core.serialization.string(),
});

export declare namespace InvitationRequest {
    interface Raw {
        name: string;
        profileUrl: string;
        sentTimeLabel: string;
        description: string;
        sharedConnections: string;
    }
}
