/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const LinkedInConnection: core.serialization.ObjectSchema<
    serializers.integrations.LinkedInConnection.Raw,
    Keet.integrations.LinkedInConnection
> = core.serialization.object({
    firstName: core.serialization.string(),
    lastName: core.serialization.string(),
    profileUrl: core.serialization.string(),
    headline: core.serialization.string(),
    publicIdentifier: core.serialization.string(),
});

export declare namespace LinkedInConnection {
    interface Raw {
        firstName: string;
        lastName: string;
        profileUrl: string;
        headline: string;
        publicIdentifier: string;
    }
}
