/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const LinkedInMessage: core.serialization.ObjectSchema<
    serializers.integrations.LinkedInMessage.Raw,
    Keet.integrations.LinkedInMessage
> = core.serialization.object({
    content: core.serialization.string(),
    sentTime: core.serialization.string(),
    from: core.serialization.string(),
});

export declare namespace LinkedInMessage {
    interface Raw {
        content: string;
        sentTime: string;
        from: string;
    }
}
