/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { LinkedInMessage } from "./LinkedInMessage";

export const LinkedInGetMessagesResponse: core.serialization.ObjectSchema<
    serializers.integrations.LinkedInGetMessagesResponse.Raw,
    Keet.integrations.LinkedInGetMessagesResponse
> = core.serialization.object({
    status: ResponseStatus,
    messages: core.serialization.list(LinkedInMessage),
});

export declare namespace LinkedInGetMessagesResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        messages: LinkedInMessage.Raw[];
    }
}
