/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const PersonSearchResult: core.serialization.ObjectSchema<
    serializers.integrations.PersonSearchResult.Raw,
    Keet.integrations.PersonSearchResult
> = core.serialization.object({
    title: core.serialization.string(),
    premium: core.serialization.string().optional(),
    primarySubtitle: core.serialization.string().optional(),
    connectionDegree: core.serialization.string(),
    summary: core.serialization.string().optional(),
    secondarySubtitle: core.serialization.string(),
    navigationUrl: core.serialization.string(),
    navigationContext: core.serialization.string().optional(),
});

export declare namespace PersonSearchResult {
    interface Raw {
        title: string;
        premium?: string | null;
        primarySubtitle?: string | null;
        connectionDegree: string;
        summary?: string | null;
        secondarySubtitle: string;
        navigationUrl: string;
        navigationContext?: string | null;
    }
}
