/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetVinVehiclesResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetVinVehiclesResponse.Raw,
    Keet.integrations.GetVinVehiclesResponse
> = core.serialization.object({
    status: ResponseStatus,
    vehicles: core.serialization.unknown(),
});

export declare namespace GetVinVehiclesResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        vehicles?: unknown;
    }
}
