/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         query: "string",
 *         isWholeFoods: true
 *     }
 */
export interface AmazonSearchItemsRequest {
    query: string;
    isWholeFoods?: boolean;
}
