/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { AmazonItem } from "./AmazonItem";

export const AmazonSearchItemsResponse: core.serialization.ObjectSchema<
    serializers.integrations.AmazonSearchItemsResponse.Raw,
    Keet.integrations.AmazonSearchItemsResponse
> = core.serialization.object({
    status: ResponseStatus,
    items: core.serialization.list(AmazonItem),
});

export declare namespace AmazonSearchItemsResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        items: AmazonItem.Raw[];
    }
}
