/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetMenusResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetMenusResponse.Raw,
    Keet.integrations.GetMenusResponse
> = core.serialization.object({
    status: ResponseStatus,
    menus: core.serialization.unknown(),
});

export declare namespace GetMenusResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        menus?: unknown;
    }
}
