/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../errors/index";
import * as KeetApi from "../../../../../index";

export class NotFoundError extends errors.KeetApiError {
    constructor(body: KeetApi.common.BaseError) {
        super({
            message: "NotFoundError",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFoundError.prototype);
    }
}
