/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../errors/index";
import * as Keet from "../../../../../index";

export class UnAuthorizedError extends errors.KeetError {
    constructor(body: Keet.common.BaseError) {
        super({
            message: "UnAuthorizedError",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnAuthorizedError.prototype);
    }
}
