/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KeetApi from "../../../../index";

/**
 * @example
 *     {
 *         linkConfig: {
 *             endUserId: "<userId>",
 *             integration: KeetApi.common.OfferedIntegrations.Instagram
 *         }
 *     }
 */
export interface CreateLinkRequest {
    linkConfig: KeetApi.common.LinkConfig;
}
