/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../index";

/**
 * @example
 *     {
 *         linkConfig: {
 *             endUserId: "<userId>",
 *             integration: "Vin",
 *             companyLogoUri: "https://example.com/logo.png"
 *         }
 *     }
 */
export interface CreateLinkRequest {
    linkConfig: Keet.common.LinkConfig;
}
