/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const SendMessageRequest: core.serialization.Schema<
    serializers.integrations.SendMessageRequest.Raw,
    Keet.integrations.SendMessageRequest
> = core.serialization.object({
    to: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace SendMessageRequest {
    interface Raw {
        to: string;
        message: string;
    }
}
