/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../index";

/**
 * @example
 *     {
 *         xAccountToken: "X-Account-Token",
 *         body: {
 *             patientId: 1,
 *             patientName: "patientName",
 *             patientPhone: "patientPhone",
 *             patientEmail: "patientEmail",
 *             clinicId: 1,
 *             doubleBooking: true,
 *             patientToBeCharged: 1,
 *             date: "2023-01-15",
 *             time: "time",
 *             notes: "notes",
 *             typeOfAppointment: "in_person",
 *             outsideScheduledHours: true,
 *             appointmentService: [{
 *                     id: 1,
 *                     duration: 1
 *                 }, {
 *                     id: 1,
 *                     duration: 1
 *                 }],
 *             duration: 1,
 *             providerId: 1,
 *             clearentEmailId: "clearentEmailId",
 *             clearentZip: "clearentZip",
 *             paymentInfo: {
 *                 creditCardNumber: 1,
 *                 expirationDate: "expirationDate",
 *                 cvv: 1
 *             }
 *         }
 *     }
 */
export interface CreateAestheticRecordsAppointmentRequest {
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
    body: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentRequest;
}
