/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../index";

/**
 * @example
 *     {
 *         xAccountToken: "X-Account-Token",
 *         providerId: 1,
 *         clinicId: 1,
 *         modality: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentModality.InPerson
 *     }
 */
export interface GetAppointmentTypesRequest {
    providerId: number;
    clinicId: number;
    modality: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentModality;
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
}
