/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         xAccountToken: "X-Account-Token",
 *         clinicId: 1,
 *         startDate: "2023-01-15",
 *         endDate: "2023-01-15",
 *         providerIds: [1, 1]
 *     }
 */
export interface GetAestheticRecordsCalendar {
    clinicId: number;
    startDate: string;
    endDate: string;
    providerIds: number[];
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
}
