/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         xAccountToken: "X-Account-Token",
 *         clinicId: 1
 *     }
 */
export interface GetProductPriceList {
    clinicId: number;
    page?: number;
    pageSize?: number;
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
}
