/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const BarGraphResponse: core.serialization.ObjectSchema<
    serializers.integrations.BarGraphResponse.Raw,
    Keet.integrations.BarGraphResponse
> = core.serialization.object({
    status: ResponseStatus,
    barGraph: core.serialization.unknown(),
});

export declare namespace BarGraphResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        barGraph?: unknown;
    }
}
