/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const CalendarResponse: core.serialization.ObjectSchema<
    serializers.integrations.CalendarResponse.Raw,
    Keet.integrations.CalendarResponse
> = core.serialization.object({
    status: ResponseStatus,
    calendar: core.serialization.unknown(),
});

export declare namespace CalendarResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        calendar?: unknown;
    }
}
