/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { ServiceBoxReceptionnaire } from "./ServiceBoxReceptionnaire";

export const EquippesResponse: core.serialization.ObjectSchema<
    serializers.integrations.EquippesResponse.Raw,
    Keet.integrations.EquippesResponse
> = core.serialization.object({
    status: ResponseStatus,
    equippes: core.serialization.list(ServiceBoxReceptionnaire),
});

export declare namespace EquippesResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        equippes: ServiceBoxReceptionnaire.Raw[];
    }
}
