/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { ServiceBoxEquippe } from "./ServiceBoxEquippe";

export const ReceptionnairesResponse: core.serialization.ObjectSchema<
    serializers.integrations.ReceptionnairesResponse.Raw,
    Keet.integrations.ReceptionnairesResponse
> = core.serialization.object({
    status: ResponseStatus,
    receptionnaires: core.serialization.list(ServiceBoxEquippe),
});

export declare namespace ReceptionnairesResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        receptionnaires: ServiceBoxEquippe.Raw[];
    }
}
