/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const ServiceBoxEquippe: core.serialization.ObjectSchema<
    serializers.integrations.ServiceBoxEquippe.Raw,
    Keet.integrations.ServiceBoxEquippe
> = core.serialization.object({
    text: core.serialization.string(),
    value: core.serialization.string(),
});

export declare namespace ServiceBoxEquippe {
    interface Raw {
        text: string;
        value: string;
    }
}
