/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const TeamIdsResponse: core.serialization.ObjectSchema<
    serializers.integrations.TeamIdsResponse.Raw,
    Keet.integrations.TeamIdsResponse
> = core.serialization.object({
    status: ResponseStatus,
    teams: core.serialization.list(core.serialization.string()),
});

export declare namespace TeamIdsResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        teams: string[];
    }
}
