/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as KeetApi from "../../../index";

export interface DeleteLinkedAccountResponse {
    status: KeetApi.common.ResponseStatus;
}
