/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../index";

export interface GetLinkedAccountResponse {
    status: Keet.common.ResponseStatus;
    linkedAccount: Keet.common.LinkedAccount;
}
