/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface ReadMessagesResponse {
    messages: Keet.integrations.WhatsAppMessage[];
    status: Keet.common.ResponseStatus;
}
