/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetXFollowingTweetsResponse {
    status: Keet.common.ResponseStatus;
    posts: Keet.integrations.XPost[];
}
