/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AestheticRecordsCategory {
    id: number;
    categoryName: string;
    tax?: number;
    isSystemCategory?: number;
    status?: number;
    copied?: number;
    systemCategoryId?: number;
    created?: string;
    modified?: string;
    catStatus?: number;
    isBundleCategory?: number;
}
