/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AestheticRecordsProductPrice {
    id: number;
    productName?: string;
    categoryId?: string;
    categoryName?: string;
    pricePerUnitMembers: number;
    pricePerUnit: number;
    productPricePerClinicId?: number;
    productImageUrl?: string;
}
