/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AestheticRecordsPatient {
    id: number;
    firstname: string;
    lastname: string;
    email?: string;
    phoneNumber?: string;
    userImageUrl?: string;
    countryName?: string;
    fullName: string;
}
