/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsDetailedProvider extends Keet.integrations.aestheticRecords.AestheticRecordsProvider {
    bioDescription?: string;
    bioName?: string;
    status: string;
    userImage?: string;
    userRoleId: number;
    roleName?: string;
    userImageUrl?: string;
    signatureUrl?: string;
}
