/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AestheticRecordsAppointmentModality = "in_person" | "virtual";

export const AestheticRecordsAppointmentModality = {
    InPerson: "in_person",
    Virtual: "virtual",
} as const;
