/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsAppointmentType {
    services: Keet.integrations.aestheticRecords.AestheticRecordsService[];
    packages?: unknown;
    clinic?: unknown;
}
