/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsWorkingHours {
    date: string;
    schedule: Keet.integrations.aestheticRecords.AestheticRecordsSchedule[];
}
