/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsAppointmentRequest {
    patientId: number;
    patientName: string;
    patientPhone: string;
    patientEmail: string;
    clinicId: number;
    doubleBooking: boolean;
    /** How much to charge the patient in dollars right now. Usually 0 for no charge at the time of booking. */
    patientToBeCharged: number;
    date: string;
    /** The time of the appointment in 24 hour format ("15:15:00") */
    time: string;
    /** Notes to attach to the appointment booking. */
    notes: string;
    typeOfAppointment: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentModality;
    outsideScheduledHours: boolean;
    /** The services that you want to book. You can get a list of available services from the [getAppointmentTypes](/api-reference/api-reference/integrations/aesthetic-records/get-appointment-types) endpoint. */
    appointmentService: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentService[];
    /** The duration of the appointment in minutes. You can find the duration of each service from the [getAppointmentTypes](/api-reference/api-reference/integrations/aesthetic-records/get-appointment-types) endpoint. */
    duration: number;
    providerId: number;
    /** The email address associated with the person paying. Usually the same as the person who is making the booking. */
    clearentEmailId: string;
    /** The zip code of the person who is paying for the booking. Usually the same as the person who is making the booking. */
    clearentZip: string;
    paymentInfo: Keet.integrations.aestheticRecords.AdditionalPaymentInfo;
}
