/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsAppointmentRecord
    extends Keet.integrations.aestheticRecords.AestheticRecordsAppointment {
    meetingId?: string;
    meetingType?: string;
    invoiceId?: number;
    packageId?: number;
    bookingId: number;
    userId: number;
    clinicId: number;
    duration: number;
    status: string;
    type: string;
    appointmentType: string;
    patientCheckedin: number;
    accepted: number;
    isConfirmed: number;
    isReschedule: number;
    appointmentTimezone: string;
    usersId: number;
    patient?: Keet.integrations.aestheticRecords.AestheticRecordsPatient;
    clinic: Keet.integrations.aestheticRecords.AestheticRecordsClinic;
    user: Keet.integrations.aestheticRecords.AestheticRecordsUser;
    appointmentServices: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentExt[];
    procedure?: unknown;
    appointmentBooking: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentBooking;
    appointmentsCheckin?: unknown;
    appointmentCancellationTransaction: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentCancellationTransaction[];
    outOfOffice?: unknown;
    color: string;
    appointmentStartTime: string;
    appointmentEndTime: string;
    appointmentDate: string;
}
