/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsDetailedClinic extends Keet.integrations.aestheticRecords.AestheticRecordsClinic {
    contactNo?: string;
    city?: string;
    country?: string;
    address?: string;
    tax?: string;
    status?: boolean;
    created?: string;
    modified?: string;
    timezone?: string;
    appointmentNotificationEmails?: unknown;
    clinicColor?: string;
    smsNotificationsPhone?: unknown;
    emailSpecialInstructions?: unknown;
    isAvailableOnline?: number;
    clinicCity?: string;
    clinicState?: string;
    clinicZipcode?: string;
    cherryPracticeId?: string;
    suiteNumber?: string;
    requiresUpdate?: boolean;
    evolusFacilityId?: unknown;
    additionalLocationBooking?: unknown;
    isAvailableEcommerce?: number;
    isTipsEnabled?: number;
    repeatMdLocationId?: unknown;
}
