/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AestheticRecordsUser {
    id: number;
    firstname: string;
    lastname: string;
    appointmentColor: string;
    roleName?: string;
    userImageUrl?: string;
    signatureUrl?: string;
    fullName: string;
}
