/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsProduct {
    id: number;
    batchId?: unknown;
    categoryId: string;
    productName: string;
    matchPattern?: unknown;
    productSku?: unknown;
    productDescription?: string;
    productImage?: unknown;
    tax?: number;
    type?: string;
    productType: string;
    productTypeLabel?: string;
    isSystemProduct: number;
    pricePerUnit?: number;
    costPerUnit?: number;
    availableStock: number;
    stockAlert: number;
    labId?: unknown;
    toxinType: string;
    fillerMoleculeId?: unknown;
    status: number;
    price?: number;
    copied?: number;
    systemProductId?: number;
    isNewProduct?: number;
    created?: string;
    modified?: string;
    isInventoryEnabled?: number;
    isStockInventoryEnabled?: number;
    isSupplierEnabled?: number;
    isTaxEnabled?: number;
    isProductActive?: number;
    costToCompany: number;
    pricePerUnitMembers?: unknown;
    countUnitsBy?: number;
    startAtUnit?: number;
    productRatioEnabled?: number;
    ratio?: number;
    productService?: string;
    keywords?: string;
    billForWholeUnit?: number;
    accountMedicalSuppliesInReports?: number;
    isAutodeductEnabled?: number;
    productPerClinic?: number;
    isEvolusProduct?: boolean;
    shopifyProductId?: number;
    shopifyProductVariantId?: number;
    shopifyDefaultClinicId?: number;
    inventoryType?: unknown;
    catId?: number;
    categoryName?: string;
    productImageUrl?: string;
    category?: Keet.integrations.aestheticRecords.AestheticRecordsCategory;
    productInventory?: unknown[];
    totalAvailableUnits?: number;
    productPricePerClinic?: Keet.integrations.aestheticRecords.AestheticRecordsProductPrice[];
}
