/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface AestheticRecordsResources {
    id: number;
    firstname: string;
    lastname: string;
    fullName: string;
    workingHours: Keet.integrations.aestheticRecords.AestheticRecordsWorkingHours[];
}
