/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AestheticRecordsAppointmentBooking {
    id: number;
    appointmentId: number;
    bookedBy: string;
    bookedByUser: number;
    bookingDatetime: string;
    bookingPaymentId: number;
    firstname: string;
    lastname: string;
    email?: string;
    phone?: string;
    appointmentNotes?: string;
    created: string;
    modified: string;
    isOverrideAllowed: number;
}
