/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetAestheticRecordsCalendarResponse {
    status: Keet.common.ResponseStatus;
    calendar: Keet.integrations.aestheticRecords.AestheticRecordsCalendar;
}
