/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetAestheticRecordsProductPriceListResponse {
    status: Keet.common.ResponseStatus;
    priceList: Keet.integrations.aestheticRecords.AestheticRecordsProductPrice[];
    pagination: Keet.integrations.aestheticRecords.AestheticRecordsPagination;
}
