/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetAppointmentTypesResponse {
    status: Keet.common.ResponseStatus;
    appointmentTypes: Keet.integrations.aestheticRecords.AestheticRecordsAppointmentType;
}
