/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetAestheticRecordsProviderAvailabilityResponse {
    status: Keet.common.ResponseStatus;
    availability: Keet.integrations.aestheticRecords.AestheticRecordsProviderAvailability;
}
