/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetAestheticRecordsClinicsResponse {
    status: Keet.common.ResponseStatus;
    clinics: Keet.integrations.aestheticRecords.AestheticRecordsDetailedClinic[];
}
