/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../../index";

export interface GetAestheticRecordsGetProductResponse {
    status: Keet.common.ResponseStatus;
    product: Keet.integrations.aestheticRecords.AestheticRecordsProduct;
}
