/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";

export const CreateVinCallResponse: core.serialization.ObjectSchema<
    serializers.integrations.vin.CreateVinCallResponse.Raw,
    Keet.integrations.vin.CreateVinCallResponse
> = core.serialization.object({
    status: ResponseStatus,
});

export declare namespace CreateVinCallResponse {
    export interface Raw {
        status: ResponseStatus.Raw;
    }
}
