/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";
import { VinUser } from "./VinUser";

export const GetUsersResponse: core.serialization.ObjectSchema<
    serializers.integrations.vin.GetUsersResponse.Raw,
    Keet.integrations.vin.GetUsersResponse
> = core.serialization.object({
    status: ResponseStatus,
    users: core.serialization.list(VinUser),
});

export declare namespace GetUsersResponse {
    export interface Raw {
        status: ResponseStatus.Raw;
        users: VinUser.Raw[];
    }
}
