/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";
import { VinDealer } from "./VinDealer";

export const GetVinDealersResponse: core.serialization.ObjectSchema<
    serializers.integrations.vin.GetVinDealersResponse.Raw,
    Keet.integrations.vin.GetVinDealersResponse
> = core.serialization.object({
    status: ResponseStatus,
    dealers: core.serialization.list(VinDealer),
});

export declare namespace GetVinDealersResponse {
    export interface Raw {
        status: ResponseStatus.Raw;
        dealers: VinDealer.Raw[];
    }
}
