/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";
import { VinLeadType } from "./VinLeadType";

export const GetVinLeadTypeResponse: core.serialization.ObjectSchema<
    serializers.integrations.vin.GetVinLeadTypeResponse.Raw,
    Keet.integrations.vin.GetVinLeadTypeResponse
> = core.serialization.object({
    status: ResponseStatus,
    leadType: core.serialization.list(VinLeadType),
});

export declare namespace GetVinLeadTypeResponse {
    export interface Raw {
        status: ResponseStatus.Raw;
        leadType: VinLeadType.Raw[];
    }
}
