/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";
import { VinSearchCustomer } from "./VinSearchCustomer";

export const SearchVinCustomersResponse: core.serialization.ObjectSchema<
    serializers.integrations.vin.SearchVinCustomersResponse.Raw,
    Keet.integrations.vin.SearchVinCustomersResponse
> = core.serialization.object({
    status: ResponseStatus,
    customers: core.serialization.list(VinSearchCustomer),
});

export declare namespace SearchVinCustomersResponse {
    export interface Raw {
        status: ResponseStatus.Raw;
        customers: VinSearchCustomer.Raw[];
    }
}
