/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinCompany: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinCompany.Raw,
    Keet.integrations.vin.VinCompany
> = core.serialization.object({
    companyName: core.serialization.string(),
    companyType: core.serialization.string(),
});

export declare namespace VinCompany {
    export interface Raw {
        companyName: string;
        companyType: string;
    }
}
