/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinCustomerContactedCodes: core.serialization.Schema<
    serializers.integrations.vin.VinCustomerContactedCodes.Raw,
    Keet.integrations.vin.VinCustomerContactedCodes
> = core.serialization.enum_(["Y", "N", "M"]);

export declare namespace VinCustomerContactedCodes {
    export type Raw = "Y" | "N" | "M";
}
