/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinCompanyType: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinCompanyType.Raw,
    Keet.integrations.vin.VinCompanyType
> = core.serialization.object({
    companyTypeName: core.serialization.string(),
    companyTypeId: core.serialization.string().optional(),
});

export declare namespace VinCompanyType {
    interface Raw {
        companyTypeName: string;
        companyTypeId?: string | null;
    }
}
