/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinDealer: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinDealer.Raw,
    Keet.integrations.vin.VinDealer
> = core.serialization.object({
    dealerId: core.serialization.property("DealerID", core.serialization.number()),
    dealerName: core.serialization.string(),
    city: core.serialization.string(),
    state: core.serialization.string(),
    setupStatus: core.serialization.string(),
    userIsIpRestricted: core.serialization.property("userIsIPRestricted", core.serialization.boolean()),
});

export declare namespace VinDealer {
    interface Raw {
        DealerID: number;
        dealerName: string;
        city: string;
        state: string;
        setupStatus: string;
        userIsIPRestricted: boolean;
    }
}
