/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinLeadType: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinLeadType.Raw,
    Keet.integrations.vin.VinLeadType
> = core.serialization.object({
    leadTypeName: core.serialization.string(),
    leadTypeId: core.serialization.string(),
});

export declare namespace VinLeadType {
    interface Raw {
        leadTypeName: string;
        leadTypeId: string;
    }
}
