/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinLeadSource: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinLeadSource.Raw,
    Keet.integrations.vin.VinLeadSource
> = core.serialization.object({
    sourceName: core.serialization.string(),
    sourceId: core.serialization.string(),
});

export declare namespace VinLeadSource {
    interface Raw {
        sourceName: string;
        sourceId: string;
    }
}
