/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinSalesVehicle: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinSalesVehicle.Raw,
    Keet.integrations.vin.VinSalesVehicle
> = core.serialization.object({
    id: core.serialization.number(),
    vehicleType: core.serialization.string(),
    make: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    year: core.serialization.number().optional(),
    stockNumber: core.serialization.unknown().optional(),
    inventoryType: core.serialization.string(),
    href: core.serialization.string().optional(),
    status: core.serialization.string(),
});

export declare namespace VinSalesVehicle {
    export interface Raw {
        id: number;
        vehicleType: string;
        make?: string | null;
        model?: string | null;
        year?: number | null;
        stockNumber?: unknown | null;
        inventoryType: string;
        href?: string | null;
        status: string;
    }
}
