/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { VinSalesAddress } from "./VinSalesAddress";

export const VinSalesLocation: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinSalesLocation.Raw,
    Keet.integrations.vin.VinSalesLocation
> = core.serialization.object({
    type: core.serialization.string(),
    name: core.serialization.string(),
    address: VinSalesAddress,
});

export declare namespace VinSalesLocation {
    export interface Raw {
        type: string;
        name: string;
        address: VinSalesAddress.Raw;
    }
}
