/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { VinSalesVehicle } from "./VinSalesVehicle";

export const VinSalesLead: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinSalesLead.Raw,
    Keet.integrations.vin.VinSalesLead
> = core.serialization.object({
    id: core.serialization.number(),
    autoId: core.serialization.number().optional(),
    vehicle: VinSalesVehicle.optional(),
    href: core.serialization.string().optional(),
});

export declare namespace VinSalesLead {
    interface Raw {
        id: number;
        autoId?: number | null;
        vehicle?: VinSalesVehicle.Raw | null;
        href?: string | null;
    }
}
