/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinSalesVisit: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinSalesVisit.Raw,
    Keet.integrations.vin.VinSalesVisit
> = core.serialization.object({
    id: core.serialization.number(),
    href: core.serialization.string(),
});

export declare namespace VinSalesVisit {
    export interface Raw {
        id: number;
        href: string;
    }
}
