/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinSearchCustomer: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinSearchCustomer.Raw,
    Keet.integrations.vin.VinSearchCustomer
> = core.serialization.object({
    customerName: core.serialization.string(),
    nameLine2: core.serialization.string().optional(),
    dealerName: core.serialization.string(),
    salesRepName: core.serialization.string(),
    homePhone: core.serialization.string().optional(),
    cellPhone: core.serialization.string().optional(),
    workPhone: core.serialization.string().optional(),
    email: core.serialization.string(),
    customerId: core.serialization.number(),
    leadId: core.serialization.number(),
    dealerId: core.serialization.number(),
});

export declare namespace VinSearchCustomer {
    interface Raw {
        customerName: string;
        nameLine2?: string | null;
        dealerName: string;
        salesRepName: string;
        homePhone?: string | null;
        cellPhone?: string | null;
        workPhone?: string | null;
        email: string;
        customerId: number;
        leadId: number;
        dealerId: number;
    }
}
