/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { VinUser } from "./VinUser";

export const VinSalesUser: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinSalesUser.Raw,
    Keet.integrations.vin.VinSalesUser
> = core.serialization
    .object({
        href: core.serialization.string().optional(),
    })
    .extend(VinUser);

export declare namespace VinSalesUser {
    interface Raw extends VinUser.Raw {
        href?: string | null;
    }
}
