/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinUser: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinUser.Raw,
    Keet.integrations.vin.VinUser
> = core.serialization.object({
    id: core.serialization.number(),
    firstName: core.serialization.string(),
    lastName: core.serialization.string().optional(),
});

export declare namespace VinUser {
    export interface Raw {
        id: number;
        firstName: string;
        lastName?: string | null;
    }
}
