/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const VinVehicle: core.serialization.ObjectSchema<
    serializers.integrations.vin.VinVehicle.Raw,
    Keet.integrations.vin.VinVehicle
> = core.serialization.object({
    stockNumber: core.serialization.string(),
    year: core.serialization.string(),
    make: core.serialization.string(),
    model: core.serialization.string(),
    trim: core.serialization.string().optional(),
    vin: core.serialization.string(),
    mileage: core.serialization.string(),
    age: core.serialization.string(),
    webPrice: core.serialization.string(),
});

export declare namespace VinVehicle {
    export interface Raw {
        stockNumber: string;
        year: string;
        make: string;
        model: string;
        trim?: string | null;
        vin: string;
        mileage: string;
        age: string;
        webPrice: string;
    }
}
