/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";
import { AmazonBusinessOrder } from "./AmazonBusinessOrder";
import { PageInfo } from "./PageInfo";

export const AmazonBusinessGetOrdersResponse: core.serialization.ObjectSchema<
    serializers.integrations.AmazonBusinessGetOrdersResponse.Raw,
    Keet.integrations.AmazonBusinessGetOrdersResponse
> = core.serialization.object({
    status: ResponseStatus,
    orders: core.serialization.list(AmazonBusinessOrder),
    pageInfo: PageInfo,
});

export declare namespace AmazonBusinessGetOrdersResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        orders: AmazonBusinessOrder.Raw[];
        pageInfo: PageInfo.Raw;
    }
}
