/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const AmazonBusinessAddress: core.serialization.ObjectSchema<
    serializers.integrations.AmazonBusinessAddress.Raw,
    Keet.integrations.AmazonBusinessAddress
> = core.serialization.object({
    name: core.serialization.string().optional(),
    addressLine1: core.serialization.string().optional(),
    addressLine2: core.serialization.string().optional(),
    country: core.serialization.string().optional(),
});

export declare namespace AmazonBusinessAddress {
    interface Raw {
        name?: string | null;
        addressLine1?: string | null;
        addressLine2?: string | null;
        country?: string | null;
    }
}
