/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Address } from "./Address";

export const Order: core.serialization.ObjectSchema<serializers.integrations.Order.Raw, Keet.integrations.Order> =
    core.serialization.object({
        date: core.serialization.date(),
        total: core.serialization.string(),
        address: Address.optional(),
        orderNumber: core.serialization.string(),
        items: core.serialization.list(core.serialization.string()),
    });

export declare namespace Order {
    interface Raw {
        date: string;
        total: string;
        address?: Address.Raw | null;
        orderNumber: string;
        items: string[];
    }
}
