/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const OrdersTimespan: core.serialization.Schema<
    serializers.integrations.OrdersTimespan.Raw,
    Keet.integrations.OrdersTimespan
> = core.serialization.enum_(["30d", "3m", "1y"]);

export declare namespace OrdersTimespan {
    type Raw = "30d" | "3m" | "1y";
}
