/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FacebookGroup: core.serialization.ObjectSchema<
    serializers.integrations.FacebookGroup.Raw,
    Keet.integrations.FacebookGroup
> = core.serialization.object({
    name: core.serialization.string(),
    numMembers: core.serialization.string().optional(),
    postsPerDay: core.serialization.string().optional(),
    privacy: core.serialization.string().optional(),
    url: core.serialization.string(),
    id: core.serialization.string(),
});

export declare namespace FacebookGroup {
    interface Raw {
        name: string;
        numMembers?: string | null;
        postsPerDay?: string | null;
        privacy?: string | null;
        url: string;
        id: string;
    }
}
