/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { FacebookGroup } from "./FacebookGroup";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const SearchGroupsResponse: core.serialization.ObjectSchema<
    serializers.integrations.SearchGroupsResponse.Raw,
    Keet.integrations.SearchGroupsResponse
> = core.serialization.object({
    groups: core.serialization.list(FacebookGroup),
    status: ResponseStatus,
});

export declare namespace SearchGroupsResponse {
    interface Raw {
        groups: FacebookGroup.Raw[];
        status: ResponseStatus.Raw;
    }
}
