/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const AppointmentType: core.serialization.Schema<
    serializers.integrations.AppointmentType.Raw,
    Keet.integrations.AppointmentType
> = core.serialization.enum_(["scheduled", "open"]);

export declare namespace AppointmentType {
    type Raw = "scheduled" | "open";
}
