/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CommPreferences: core.serialization.Schema<
    serializers.integrations.CommPreferences.Raw,
    Keet.integrations.CommPreferences
> = core.serialization.enum_(["None", "Email", "Text", "Both"]);

export declare namespace CommPreferences {
    type Raw = "None" | "Email" | "Text" | "Both";
}
