/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetArrivalWindowResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetArrivalWindowResponse.Raw,
    Keet.integrations.GetArrivalWindowResponse
> = core.serialization.object({
    status: ResponseStatus,
    arrivalWindow: core.serialization.unknown(),
});

export declare namespace GetArrivalWindowResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        arrivalWindow?: unknown;
    }
}
