/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetCustomerTypesResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetCustomerTypesResponse.Raw,
    Keet.integrations.GetCustomerTypesResponse
> = core.serialization.object({
    status: ResponseStatus,
    customerTypes: core.serialization.unknown(),
});

export declare namespace GetCustomerTypesResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        customerTypes?: unknown;
    }
}
