/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetCalendarResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetCalendarResponse.Raw,
    Keet.integrations.GetCalendarResponse
> = core.serialization.object({
    status: ResponseStatus,
    calendar: core.serialization.unknown(),
});

export declare namespace GetCalendarResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        calendar?: unknown;
    }
}
