/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetDiagnosticFeeResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetDiagnosticFeeResponse.Raw,
    Keet.integrations.GetDiagnosticFeeResponse
> = core.serialization.object({
    status: ResponseStatus,
    diagnosticFee: core.serialization.unknown(),
});

export declare namespace GetDiagnosticFeeResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        diagnosticFee?: unknown;
    }
}
