/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetInvoiceTypesResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetInvoiceTypesResponse.Raw,
    Keet.integrations.GetInvoiceTypesResponse
> = core.serialization.object({
    status: ResponseStatus,
    invoiceTypes: core.serialization.unknown(),
});

export declare namespace GetInvoiceTypesResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        invoiceTypes?: unknown;
    }
}
