/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetServiceCallTypeResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetServiceCallTypeResponse.Raw,
    Keet.integrations.GetServiceCallTypeResponse
> = core.serialization.object({
    status: ResponseStatus,
    serviceCallType: core.serialization.unknown(),
});

export declare namespace GetServiceCallTypeResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        serviceCallType?: unknown;
    }
}
