/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ResponseStatus } from "../../../../common/resources/types/types/ResponseStatus";

export const GetServiceCallStatusResponse: core.serialization.ObjectSchema<
    serializers.integrations.GetServiceCallStatusResponse.Raw,
    Keet.integrations.GetServiceCallStatusResponse
> = core.serialization.object({
    status: ResponseStatus,
    serviceCallStatus: core.serialization.unknown(),
});

export declare namespace GetServiceCallStatusResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        serviceCallStatus?: unknown;
    }
}
