/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const MultiTechOrNot: core.serialization.Schema<
    serializers.integrations.MultiTechOrNot.Raw,
    Keet.integrations.MultiTechOrNot
> = core.serialization.enum_(["Add_New_Technician", ""]);

export declare namespace MultiTechOrNot {
    type Raw = "Add_New_Technician" | "";
}
