/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FacebookGroup {
    name: string;
    numMembers?: string;
    postsPerDay?: string;
    privacy?: string;
    url: string;
    id: string;
}
