/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface SearchGroupsResponse {
    groups: Keet.integrations.FacebookGroup[];
    status: Keet.common.ResponseStatus;
}
