/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface AmazonGetBuyAgainResponse {
    status: Keet.common.ResponseStatus;
    items: Keet.integrations.AmazonItem[];
}
