/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const MakePaymentRequest: core.serialization.Schema<
    serializers.integrations.MakePaymentRequest.Raw,
    Keet.integrations.MakePaymentRequest
> = core.serialization.object({
    amount: core.serialization.number(),
    description: core.serialization.string(),
});

export declare namespace MakePaymentRequest {
    interface Raw {
        amount: number;
        description: string;
    }
}
