/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../index";

/**
 * @example
 *     {
 *         origin: {
 *             addressLine1: "string",
 *             addressLine2: "string"
 *         },
 *         destination: {
 *             addressLine1: "string",
 *             addressLine2: "string"
 *         },
 *         carType: Keet.integrations.UberCarTypes.UberX
 *     }
 */
export interface OrderRide {
    origin: Keet.integrations.UberAddress;
    destination: Keet.integrations.UberAddress;
    carType: Keet.integrations.UberCarTypes;
}
