/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         xAccountToken: "string",
 *         amount: 1,
 *         description: "string"
 *     }
 */
export interface MakePaymentRequest {
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
    amount: number;
    description: string;
}
