/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         amount: 1,
 *         description: "string"
 *     }
 */
export interface MakePaymentRequest {
    amount: number;
    description: string;
}
