/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         date: "string",
 *         receptionnnaire: "string",
 *         equipe: "string"
 *     }
 */
export interface GetServiceBoxCalendar {
    date: string;
    receptionnnaire: string;
    equipe: string;
}
