/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         equipe: "string"
 *     }
 */
export interface GetServiceBoxReceptionnaires {
    equipe: string;
}
