/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Keet from "../../../../../api/index";
import * as core from "../../../../../core";

export const GetTokenRequest: core.serialization.Schema<serializers.GetTokenRequest.Raw, Keet.GetTokenRequest> =
    core.serialization.object({
        publicToken: core.serialization.string(),
    });

export declare namespace GetTokenRequest {
    export interface Raw {
        publicToken: string;
    }
}
