/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         boardId: "string",
 *         calendarId: "string"
 *     }
 */
export interface GetCalendar {
    boardId: string;
    calendarId: string;
}
