/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         firstName: "string",
 *         lastName: "string"
 *     }
 */
export interface SearchCustomer {
    firstName: string;
    lastName: string;
}
