/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         xAccountToken: "string",
 *         page: 1,
 *         limit: 1
 *     }
 */
export interface GetOrdersRequest {
    page?: number;
    limit?: number;
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
}
