/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         itemUrl: "string",
 *         asin: "string"
 *     }
 */
export interface OrderItem {
    itemUrl?: string;
    asin?: string;
}
