/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UberCarTypes =
    | "UberX"
    | "UberXL"
    | "Comfort"
    | "Share"
    | "ComfortElectric"
    | "Green"
    | "UberPet"
    | "UberBlack"
    | "UberBlackSUV"
    | "WAV";

export const UberCarTypes = {
    UberX: "UberX",
    UberXl: "UberXL",
    Comfort: "Comfort",
    Share: "Share",
    ComfortElectric: "ComfortElectric",
    Green: "Green",
    UberPet: "UberPet",
    UberBlack: "UberBlack",
    UberBlackSuv: "UberBlackSUV",
    Wav: "WAV",
} as const;
