/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as KeetApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const BaseError: core.serialization.ObjectSchema<serializers.common.BaseError.Raw, KeetApi.common.BaseError> =
    core.serialization.object({
        error: core.serialization.string(),
    });

export declare namespace BaseError {
    interface Raw {
        error: string;
    }
}
