/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CommPreferences = "None" | "Email" | "Text" | "Both";

export const CommPreferences = {
    None: "None",
    Email: "Email",
    Text: "Text",
    Both: "Both",
} as const;
