/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetBillingTermsResponse {
    status: Keet.common.ResponseStatus;
    billingTerms?: unknown;
}
