/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetTechniciansResponse {
    status: Keet.common.ResponseStatus;
    technicians?: unknown;
}
