/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type MultiTechOrNot = "Add_New_Technician" | "";

export const MultiTechOrNot = {
    AddNewTechnician: "Add_New_Technician",
    Empty: "",
} as const;
