/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PhoneType = "Home" | "Work" | "Cell" | "Fax" | "Other";

export const PhoneType = {
    Home: "Home",
    Work: "Work",
    Cell: "Cell",
    Fax: "Fax",
    Other: "Other",
} as const;
