/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface ServiceCallRequest {
    locationContactInfoId?: string;
    appointmentType: Keet.integrations.AppointmentType;
    openServiceCallDate?: string;
    serviceCallTypeId: number;
    hours: string;
    minutes: string;
    arrivalWindow: string;
    diagnosticFee: number;
    serviceCallStatus: string;
    leadSourceId: number;
    poNumber?: string;
    description: string;
    notes?: string;
    datepicker1: string;
    dispatchBoardId: number;
    callTypeId?: string;
    startTime?: string;
    endTime?: string;
    date?: string;
    technicianId?: number;
    sendEmail: number;
    doNotEmail?: number;
    arrivalWindowId: number;
    id?: string;
    newCustomer: number;
    customerFirstName: string;
    customerLastName: string;
    customerCompanyName: string;
    customerFullName: string;
    newServiceCallDefLeadSourId: number;
    appointmentSaveFrom: string;
    selectedMultiTechSameCall?: Keet.integrations.MutliTech[];
    primaryOpenCallTech?: string;
    selectedMultiTechSameCallOrNot?: Keet.integrations.MultiTechOrNot;
    isMultipleTech?: string;
    isPrimaryTechId?: number;
    isPrimaryTech?: string;
    isSecondaryServiceCallData: number;
}
