/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const AestheticRecordsAppointmentBooking: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsAppointmentBooking.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsAppointmentBooking
> = core.serialization.object({
    id: core.serialization.number(),
    appointmentId: core.serialization.property("appointment_id", core.serialization.number()),
    bookedBy: core.serialization.property("booked_by", core.serialization.string()),
    bookedByUser: core.serialization.property("booked_by_user", core.serialization.number()),
    bookingDatetime: core.serialization.property("booking_datetime", core.serialization.string()),
    bookingPaymentId: core.serialization.property("booking_payment_id", core.serialization.number()),
    firstname: core.serialization.string(),
    lastname: core.serialization.string(),
    email: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    appointmentNotes: core.serialization.property("appointment_notes", core.serialization.string().optional()),
    created: core.serialization.string(),
    modified: core.serialization.string(),
    isOverrideAllowed: core.serialization.property("is_override_allowed", core.serialization.number()),
});

export declare namespace AestheticRecordsAppointmentBooking {
    export interface Raw {
        id: number;
        appointment_id: number;
        booked_by: string;
        booked_by_user: number;
        booking_datetime: string;
        booking_payment_id: number;
        firstname: string;
        lastname: string;
        email?: string | null;
        phone?: string | null;
        appointment_notes?: string | null;
        created: string;
        modified: string;
        is_override_allowed: number;
    }
}
