/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const AestheticRecordsAppointmentService: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsAppointmentService.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsAppointmentService
> = core.serialization.object({
    id: core.serialization.number(),
    duration: core.serialization.number(),
    confirmDeposit: core.serialization.boolean().optional(),
});

export declare namespace AestheticRecordsAppointmentService {
    interface Raw {
        id: number;
        duration: number;
        confirmDeposit?: boolean | null;
    }
}
