/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const AestheticRecordsAppointment: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsAppointment.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsAppointment
> = core.serialization.object({
    id: core.serialization.number(),
    patientId: core.serialization.property("patient_id", core.serialization.number()),
    appointmentDatetime: core.serialization.property("appointment_datetime", core.serialization.string()),
    appointmentStartOn: core.serialization.property("appointment_start_on", core.serialization.string()),
    appointmentEndtime: core.serialization.property("appointment_endtime", core.serialization.string()),
    date: core.serialization.string().optional(),
    time: core.serialization.string().optional(),
    formatTime: core.serialization.property("format_time", core.serialization.string().optional()),
    formatDate: core.serialization.property("format_date", core.serialization.string().optional()),
    meetingUrl: core.serialization.property("meeting_url", core.serialization.string().optional()),
    startTime: core.serialization.property("start_time", core.serialization.string().optional()),
    endTime: core.serialization.property("end_time", core.serialization.string().optional()),
    appointmentTimezoneAbbr: core.serialization.property(
        "appointment_timezone_abbr",
        core.serialization.string().optional(),
    ),
    displayStatus: core.serialization.property("display_status", core.serialization.string().optional()),
});

export declare namespace AestheticRecordsAppointment {
    export interface Raw {
        id: number;
        patient_id: number;
        appointment_datetime: string;
        appointment_start_on: string;
        appointment_endtime: string;
        date?: string | null;
        time?: string | null;
        format_time?: string | null;
        format_date?: string | null;
        meeting_url?: string | null;
        start_time?: string | null;
        end_time?: string | null;
        appointment_timezone_abbr?: string | null;
        display_status?: string | null;
    }
}
