/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { AestheticRecordsClinic } from "./AestheticRecordsClinic";
import { AestheticRecordsProvider } from "./AestheticRecordsProvider";
import { AestheticRecordsAppointmentRecord } from "./AestheticRecordsAppointmentRecord";
import { AestheticRecordsResources } from "./AestheticRecordsResources";

export const AestheticRecordsCalendar: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsCalendar.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsCalendar
> = core.serialization.object({
    clinics: core.serialization.list(AestheticRecordsClinic),
    providers: core.serialization.list(AestheticRecordsProvider),
    clinicId: core.serialization.property("clinic_id", core.serialization.number().optional()),
    appointments: core.serialization.list(AestheticRecordsAppointmentRecord),
    resources: core.serialization.list(AestheticRecordsResources),
    doctorIds: core.serialization.property("doctor_ids", core.serialization.list(core.serialization.number())),
    serviceIds: core.serialization.property(
        "service_ids",
        core.serialization.list(core.serialization.unknown()).optional()
    ),
    clinicOpensAt: core.serialization.string(),
    clinicClosesAt: core.serialization.string(),
    opensAt: core.serialization.string(),
    closesAt: core.serialization.string(),
    clinicTimezone: core.serialization.property("clinic_timezone", core.serialization.string()),
});

export declare namespace AestheticRecordsCalendar {
    interface Raw {
        clinics: AestheticRecordsClinic.Raw[];
        providers: AestheticRecordsProvider.Raw[];
        clinic_id?: number | null;
        appointments: AestheticRecordsAppointmentRecord.Raw[];
        resources: AestheticRecordsResources.Raw[];
        doctor_ids: number[];
        service_ids?: unknown[] | null;
        clinicOpensAt: string;
        clinicClosesAt: string;
        opensAt: string;
        closesAt: string;
        clinic_timezone: string;
    }
}
