/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const AestheticRecordsProvider: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsProvider.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsProvider
> = core.serialization.object({
    id: core.serialization.number(),
    firstname: core.serialization.string(),
    lastname: core.serialization.string(),
    fullName: core.serialization.property("full_name", core.serialization.string()),
});

export declare namespace AestheticRecordsProvider {
    interface Raw {
        id: number;
        firstname: string;
        lastname: string;
        full_name: string;
    }
}
