/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const AestheticRecordsServiceAppointment: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsServiceAppointment.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsServiceAppointment
> = core.serialization.object({
    id: core.serialization.number(),
    name: core.serialization.string(),
    duration: core.serialization.number(),
    mins: core.serialization.number(),
    hours: core.serialization.number(),
});

export declare namespace AestheticRecordsServiceAppointment {
    interface Raw {
        id: number;
        name: string;
        duration: number;
        mins: number;
        hours: number;
    }
}
