/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const AestheticRecordsAppointmentCancellationTransaction: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsAppointmentCancellationTransaction.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsAppointmentCancellationTransaction
> = core.serialization.object({
    id: core.serialization.number(),
    appointmentId: core.serialization.property("appointment_id", core.serialization.number()),
    status: core.serialization.string().optional(),
    authorizeTransactionId: core.serialization.property(
        "authorize_transaction_id",
        core.serialization.string().optional()
    ),
    chargeTransactionId: core.serialization.property("charge_transaction_id", core.serialization.string().optional()),
    cancellationFee: core.serialization.property("cancellation_fee", core.serialization.number()),
    refundTransactionId: core.serialization.property("refund_transaction_id", core.serialization.string().optional()),
    created: core.serialization.string(),
    modified: core.serialization.string(),
    refundDate: core.serialization.property("refund_date", core.serialization.string().optional()),
    stripeUserId: core.serialization.property("stripe_user_id", core.serialization.string().optional()),
    chargeDays: core.serialization.property("charge_days", core.serialization.number()),
});

export declare namespace AestheticRecordsAppointmentCancellationTransaction {
    interface Raw {
        id: number;
        appointment_id: number;
        status?: string | null;
        authorize_transaction_id?: string | null;
        charge_transaction_id?: string | null;
        cancellation_fee: number;
        refund_transaction_id?: string | null;
        created: string;
        modified: string;
        refund_date?: string | null;
        stripe_user_id?: string | null;
        charge_days: number;
    }
}
