/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { AestheticRecordsSchedule } from "./AestheticRecordsSchedule";

export const AestheticRecordsWorkingHours: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.AestheticRecordsWorkingHours.Raw,
    Keet.integrations.aestheticRecords.AestheticRecordsWorkingHours
> = core.serialization.object({
    date: core.serialization.string(),
    schedule: core.serialization.list(AestheticRecordsSchedule),
});

export declare namespace AestheticRecordsWorkingHours {
    interface Raw {
        date: string;
        schedule: AestheticRecordsSchedule.Raw[];
    }
}
