/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";

export const GetAestheticRecordsAccountData: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.GetAestheticRecordsAccountData.Raw,
    Keet.integrations.aestheticRecords.GetAestheticRecordsAccountData
> = core.serialization.object({
    status: ResponseStatus,
    accountData: core.serialization.unknown(),
});

export declare namespace GetAestheticRecordsAccountData {
    export interface Raw {
        status: ResponseStatus.Raw;
        accountData?: unknown;
    }
}
