/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";
import { AestheticRecordsClientGet } from "./AestheticRecordsClientGet";

export const GetAestheticRecordsClientResponse: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.GetAestheticRecordsClientResponse.Raw,
    Keet.integrations.aestheticRecords.GetAestheticRecordsClientResponse
> = core.serialization.object({
    status: ResponseStatus,
    client: AestheticRecordsClientGet,
});

export declare namespace GetAestheticRecordsClientResponse {
    interface Raw {
        status: ResponseStatus.Raw;
        client: AestheticRecordsClientGet.Raw;
    }
}
