/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as Keet from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";
import { ResponseStatus } from "../../../../../../common/resources/types/types/ResponseStatus";
import { AestheticRecordsProviderAvailability } from "./AestheticRecordsProviderAvailability";

export const GetAestheticRecordsProviderAvailabilityResponse: core.serialization.ObjectSchema<
    serializers.integrations.aestheticRecords.GetAestheticRecordsProviderAvailabilityResponse.Raw,
    Keet.integrations.aestheticRecords.GetAestheticRecordsProviderAvailabilityResponse
> = core.serialization.object({
    status: ResponseStatus,
    availability: AestheticRecordsProviderAvailability,
});

export declare namespace GetAestheticRecordsProviderAvailabilityResponse {
    export interface Raw {
        status: ResponseStatus.Raw;
        availability: AestheticRecordsProviderAvailability.Raw;
    }
}
