/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         accountToken: "string"
 *     }
 */
export interface DeleteLinkedAccountRequest {
    /**
     * The account token that is associated with the end user linked to this account
     */
    accountToken: string;
}
