/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         publicToken: "..."
 *     }
 */
export interface GetTokenRequest {
    publicToken: string;
}
