/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as KeetApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const Comments: core.serialization.ObjectSchema<
    serializers.integrations.Comments.Raw,
    KeetApi.integrations.Comments
> = core.serialization.object({
    count: core.serialization.number(),
    userCommentedOrLiked: core.serialization.boolean(),
});

export declare namespace Comments {
    interface Raw {
        count: number;
        userCommentedOrLiked: boolean;
    }
}
