/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Keet from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const Likes: core.serialization.ObjectSchema<serializers.integrations.Likes.Raw, Keet.integrations.Likes> =
    core.serialization.object({
        count: core.serialization.number(),
        userCommentedOrLiked: core.serialization.boolean(),
    });

export declare namespace Likes {
    interface Raw {
        count: number;
        userCommentedOrLiked: boolean;
    }
}
