/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as KeetApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Payload } from "./Payload";
import { User } from "./User";

export const Title: core.serialization.ObjectSchema<serializers.integrations.Title.Raw, KeetApi.integrations.Title> =
    core.serialization.object({
        titleType: core.serialization.string(),
        payload: Payload,
        receiver: User,
        sender: User,
    });

export declare namespace Title {
    interface Raw {
        titleType: string;
        payload: Payload.Raw;
        receiver: User.Raw;
        sender: User.Raw;
    }
}
