/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetSalesAppointmentsResponse {
    status: Keet.common.ResponseStatus;
    appointments?: unknown;
}
