/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetVinVehiclesResponse {
    status: Keet.common.ResponseStatus;
    vehicles?: unknown;
}
