/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VinCustomer {
    homePhone: string;
    workPhone: string;
    cellPhone: string;
    firstName: string;
    middleName: string;
    lastName: string;
    email: string;
    vehicleNumber: string;
}
