/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const AddToCart: core.serialization.Schema<serializers.integrations.AddToCart.Raw, Keet.integrations.AddToCart> =
    core.serialization.object({
        asin: core.serialization.string().optional(),
        itemUrl: core.serialization.string().optional(),
    });

export declare namespace AddToCart {
    interface Raw {
        asin?: string | null;
        itemUrl?: string | null;
    }
}
