/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const OrderAmazonItem: core.serialization.Schema<
    serializers.integrations.OrderAmazonItem.Raw,
    Keet.integrations.OrderAmazonItem
> = core.serialization.object({
    itemUrl: core.serialization.string(),
});

export declare namespace OrderAmazonItem {
    interface Raw {
        itemUrl: string;
    }
}
