/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Integrations } from "./api/resources/integrations/client/Client";
import { Link } from "./api/resources/link/client/Client";
import { LinkedAccounts } from "./api/resources/linkedAccounts/client/Client";

export declare namespace KeetClient {
    interface Options {
        token: core.Supplier<core.BearerToken>;
        /** Override the X-Account-Token header */
        accountToken?: core.Supplier<string | undefined>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Account-Token header */
        accountToken?: string | undefined;
    }
}

export class KeetClient {
    constructor(protected readonly _options: KeetClient.Options) {}

    protected _integrations: Integrations | undefined;

    public get integrations(): Integrations {
        return (this._integrations ??= new Integrations(this._options));
    }

    protected _link: Link | undefined;

    public get link(): Link {
        return (this._link ??= new Link(this._options));
    }

    protected _linkedAccounts: LinkedAccounts | undefined;

    public get linkedAccounts(): LinkedAccounts {
        return (this._linkedAccounts ??= new LinkedAccounts(this._options));
    }
}
