/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const KeetApiEnvironment = {
    Production: "https://api.trykeet.com",
} as const;

export type KeetApiEnvironment = typeof KeetApiEnvironment.Production;
