/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const KeetEnvironment = {
    Production: "https://api.trykeet.com",
} as const;

export type KeetEnvironment = typeof KeetEnvironment.Production;
