/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         profileUrl: "string"
 *     }
 */
export interface AcceptConnectionInvitation {
    profileUrl: string;
}
