/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         to: "string",
 *         content: "string"
 *     }
 */
export interface SendMessage {
    /** The profile name of the person to send the message to. For example for the account with the url "https://www.linkedin.com/in/zacharyashen/" the profile name would be "zacharyashen" */
    to: string;
    content: string;
}
