/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface GetConnectionsResult {
    status: Keet.common.ResponseStatus;
    connections: Keet.integrations.LinkedInConnection[];
}
