/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InvitationRequest {
    name: string;
    profileUrl: string;
    sentTimeLabel: string;
    description: string;
    sharedConnections: string;
}
