/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface LinkedInGetMessagesResponse {
    status: Keet.common.ResponseStatus;
    messages: Keet.integrations.LinkedInMessage[];
}
