/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface SearchResponse {
    status: Keet.common.ResponseStatus;
    results: Keet.integrations.PersonSearchResult[];
}
