/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface BarGraphResponse {
    status: Keet.common.ResponseStatus;
    barGraph?: unknown;
}
