/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface CalendarResponse {
    status: Keet.common.ResponseStatus;
    calendar?: unknown;
}
