/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface ReceptionnairesResponse {
    status: Keet.common.ResponseStatus;
    receptionnaires: Keet.integrations.ServiceBoxEquippe[];
}
