/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { VinCustomerContactedCodes } from "../../resources/types/types/VinCustomerContactedCodes";
import { VinNumberDialedCodes } from "../../resources/types/types/VinNumberDialedCodes";
import { VinNextCallTimeSpanTypes } from "../../resources/types/types/VinNextCallTimeSpanTypes";

export const CreateVinCall: core.serialization.Schema<
    serializers.integrations.vin.CreateVinCall.Raw,
    Omit<Keet.integrations.vin.CreateVinCall, "xAccountToken">
> = core.serialization.object({
    leadId: core.serialization.string(),
    customerId: core.serialization.string(),
    dealerId: core.serialization.string(),
    phoneNumber: core.serialization.string(),
    note: core.serialization.string(),
    customerContactedCode: VinCustomerContactedCodes,
    numberDialedCode: VinNumberDialedCodes,
    nextCallTimeFrame: core.serialization.number(),
    nextCallTimeSpanType: VinNextCallTimeSpanTypes,
    outbound: core.serialization.boolean(),
});

export declare namespace CreateVinCall {
    export interface Raw {
        leadId: string;
        customerId: string;
        dealerId: string;
        phoneNumber: string;
        note: string;
        customerContactedCode: VinCustomerContactedCodes.Raw;
        numberDialedCode: VinNumberDialedCodes.Raw;
        nextCallTimeFrame: number;
        nextCallTimeSpanType: VinNextCallTimeSpanTypes.Raw;
        outbound: boolean;
    }
}
