/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Keet from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const CreateVinLead: core.serialization.Schema<
    serializers.integrations.vin.CreateVinLead.Raw,
    Omit<Keet.integrations.vin.CreateVinLead, "xAccountToken">
> = core.serialization.object({
    customerId: core.serialization.string(),
    dealerId: core.serialization.string(),
    vehicleStockNumber: core.serialization.string(),
    sourceId: core.serialization.string(),
    leadTypeId: core.serialization.string(),
    inShowroom: core.serialization.boolean().optional(),
});

export declare namespace CreateVinLead {
    export interface Raw {
        customerId: string;
        dealerId: string;
        vehicleStockNumber: string;
        sourceId: string;
        leadTypeId: string;
        inShowroom?: boolean | null;
    }
}
