/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DispatchMeAddress {
    street1: string;
    street2: string;
    city: string;
    state: string;
    postalCode: string;
    district: string;
    county: string;
    country: string;
    formattedAddress: string;
    timezone: string;
    latitude: number;
    longitude: number;
}
