/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../index";

export interface DispatchMeCustomer {
    firstName: string;
    lastName: string;
    organizationId: string;
    companyName: string;
    billingAddress: Keet.integrations.DispatchMeAddress;
    homeAddress: Keet.integrations.DispatchMeAddress;
    email: string;
    notes: string;
    phoneNumbers: Keet.integrations.DispatchMePhoneNumber[];
    labels: string[];
}
