/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DispatchMeAppointment {
    duration: number;
    time: string;
    userId: number;
    secondaryUserIds: number[];
    type: string;
    organizationId: number;
    jobId: number;
}
