/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         xAccountToken: "X-Account-Token",
 *         customerId: "customerId",
 *         dealerId: "dealerId",
 *         vehicleStockNumber: "vehicleStockNumber",
 *         sourceId: "sourceId",
 *         leadTypeId: "leadTypeId"
 *     }
 */
export interface CreateVinLead {
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
    customerId: string;
    dealerId: string;
    vehicleStockNumber: string;
    sourceId: string;
    leadTypeId: string;
    inShowroom?: boolean;
}
