/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Keet from "../../../../../../index";

/**
 * @example
 *     {
 *         xAccountToken: "X-Account-Token",
 *         customer: {
 *             homePhone: "homePhone",
 *             firstName: "firstName",
 *             lastName: "lastName",
 *             email: "email",
 *             vehicleNumber: "vehicleNumber"
 *         },
 *         dealerId: "dealerId",
 *         sourceName: "sourceName",
 *         sourceId: "sourceId",
 *         leadTypeId: "leadTypeId"
 *     }
 */
export interface CreateVinCustomer {
    /**
     * The account token that is associated with the end user linked to this account
     */
    xAccountToken: string;
    customer: Keet.integrations.vin.VinCustomer;
    dealerId: string;
    sourceName: string;
    sourceId: string;
    /** Defaults to authenticated user */
    vinUser?: Keet.integrations.vin.VinUser;
    leadTypeId: string;
    notes?: string;
}
