/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         leadId: "string",
 *         customerId: "string",
 *         dealerId: "string",
 *         description: "string",
 *         endDate: "string",
 *         startDate: "string",
 *         assignedUserId: "string"
 *     }
 */
export interface CreateVinAppointmentRequest {
    leadId: string;
    customerId: string;
    dealerId: string;
    description: string;
    endDate: string;
    startDate: string;
    assignedUserId: string;
}
