/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         date: "string"
 *     }
 */
export interface GetVinAppointmentsRequest {
    date: string;
}
